countries = {
    'DZ': 'Algeria',
    'AO': 'Angola',
    'AR': 'Argentina',
    'AU': 'Australia',
    'AT': 'Austria',
    'BH': 'Bahrain',
    'BY': 'Belarus',
    'BE': 'Belgium',
    'BR': 'Brazil',
    'BG': 'Bulgaria',
    'CA': 'Canada',
    'CL': 'Chile',
    'CN': 'China',
    'CO': 'Colombia',
    'CD': 'Democratic Republic of Congo',
    'CI': 'Cote dIvoire',
    'HR': 'Croatia',
    'CZ': 'Czech Republic',
    'DK': 'Denmark',
    'EG': 'Egypt',
    'EE': 'Estonia',
    'FI': 'Finland',
    'FR': 'France',
    'GH': 'Ghana',
    'GR': 'Greece',
    'PL': 'Poland',
    'DE': 'Germany',
    'CH': 'Swizerland',
    'TR': 'Turkey',
    'UA': 'Ukraine',
    'UK': 'United Kingdom',
    'US': 'United States',
    'HK': 'Hong Kong',
    'HQ': 'HQ',
    'HU': 'Hungary',
    'IN': 'India',
    'ID': 'Indonesia',
    'IQ': 'Iraq',
    'IE': 'Ireland',
    'IL': 'Israel',
    'IT': 'Italy',
    'JP': 'Japan',
    'JO': 'Jordan',
    'KZ': 'Kazakhstan',
    'KE': 'Kenya',
    'KW': 'Kuwait',
    'LV': 'Latvia',
    'LT': 'Lithuania',
    'MY': 'Malaysia',
    'MX': 'Mexico',
    'MA': 'Morocco',
    'MZ': 'Mozambique',
    'NL': 'Netherlands',
    'NZ': 'New Zealand',
    'NO': 'Norway',
    'OM': 'Oman',
    'PK': 'Pakistan',
    'PA': 'Panama',
    'PE': 'Peru',
    'PH': 'Philippines',
    'PT': 'Portugal',
    'QA': 'Qatar',
    'RO': 'Romania',
    'RU': 'Russia',
    'SA': 'Saudi Arabia',
    'SG': 'Singapore',
    'SK': 'Slovakia',
    'SI': 'Slovenia',
    'ZA': 'South Africa',
    'KR': 'South Korea',
    'ES': 'Spain',
    'SE': 'Sweden',
    'TZ': 'Tanzania, United Republic of',
    'TH': 'Thailand',
    'AE': 'United Arab Emirates',
    'VN': 'Vietnam',
    '01': 'Cluster Brazil',
    '02': 'Cluster China',
    '03': 'Cluster Germany',
    '04': 'Cluster Italy',
    '05': 'Cluster Singapore',
    '06': 'Cluster Sweden',
    '07': 'Cluster Switzerland',
    '08': 'Cluster UAE',
    '09': 'Cluster UK',
    '10': 'Cluster US',
    '11': 'Cluster CSE'
             }


units = {'Hub_Office': 'HR Center',
         'Front_Office': 'Front Office'
         }

Centers = {'KRK': 'Krakow',
         'TLL': 'Tallinn',
         'BGL': 'Bangalore',
         'SPL': 'Sao Paolo'
         }